using System;using System.Collections.Concurrent;using System.IO;using System.Net;using System.Net.Sockets;using System.Text;using System.Threading;
namespace Orbit {
 internal sealed class LoopbackHostProxy:IDisposable {
  const int MaxHeader=32768,MaxBody=65536;readonly int target;readonly TcpListener listener;readonly Thread accept;readonly SemaphoreSlim slots=new SemaphoreSlim(16);readonly ConcurrentDictionary<TcpClient,byte> clients=new ConcurrentDictionary<TcpClient,byte>();volatile bool stopped;
  public int Port{get;private set;}
  public LoopbackHostProxy(int targetPort){target=targetPort;listener=new TcpListener(IPAddress.Loopback,0);listener.Start(16);Port=((IPEndPoint)listener.LocalEndpoint).Port;accept=new Thread(Accept){IsBackground=true};accept.Start();}
  void Accept(){while(!stopped)try{var c=listener.AcceptTcpClient();if(!slots.Wait(0)){c.Close();continue;}clients[c]=0;ThreadPool.QueueUserWorkItem(_=>{try{Relay(c);}catch{}finally{byte ignored;clients.TryRemove(c,out ignored);try{c.Close();}catch{}slots.Release();}});}catch{if(stopped)return;}}
  void Relay(TcpClient client){using(var input=client.GetStream()){input.ReadTimeout=5000;input.WriteTimeout=35000;byte[] header=ReadHeader(input);string rewritten;int body;if(header==null||!Rewrite(header,out rewritten,out body))return;bool stream=body>MaxBody;byte[] payload=stream?null:ReadExact(input,body,10000);if(!stream&&payload==null)return;using(var upstream=new TcpClient()){upstream.SendTimeout=stream?30000:5000;upstream.ReceiveTimeout=35000;upstream.Connect(IPAddress.Loopback,target);using(var output=upstream.GetStream()){byte[] head=Encoding.ASCII.GetBytes(rewritten);output.Write(head,0,head.Length);if(stream){if(!CopyExact(input,output,body,15000))return;}else if(body>0)output.Write(payload,0,payload.Length);output.Flush();output.CopyTo(input);}}}}
  bool Rewrite(byte[] raw,out string result,out int body){result=null;body=0;string text=Encoding.ASCII.GetString(raw);if(!text.EndsWith("\r\n\r\n",StringComparison.Ordinal))return false;string[] lines=text.Substring(0,text.Length-4).Split(new[]{"\r\n"},StringSplitOptions.None);if(lines.Length<1||!ValidRequestLine(lines[0]))return false;var clean=new StringBuilder(lines[0]);bool lengthSeen=false;for(int i=1;i<lines.Length;i++){string line=lines[i];int colon=line.IndexOf(':');if(colon<=0)return false;string name=line.Substring(0,colon).Trim();string value=line.Substring(colon+1).Trim();if(name.Length==0)return false;if(String.Equals(name,"Transfer-Encoding",StringComparison.OrdinalIgnoreCase))return false;if(String.Equals(name,"Content-Length",StringComparison.OrdinalIgnoreCase)){long parsed;if(lengthSeen||!Int64.TryParse(value,out parsed)||parsed<0||parsed>(UploadLine(lines[0])?RemoteServer.MaxUpload:MaxBody))return false;lengthSeen=true;body=(int)parsed;continue;}if(String.Equals(name,"Host",StringComparison.OrdinalIgnoreCase)||String.Equals(name,"Connection",StringComparison.OrdinalIgnoreCase))continue;clean.Append("\r\n").Append(name).Append(": ").Append(value);}clean.Append("\r\nHost: 127.0.0.1:").Append(target).Append("\r\nConnection: close");if(lengthSeen)clean.Append("\r\nContent-Length: ").Append(body);clean.Append("\r\n\r\n");result=clean.ToString();return Encoding.ASCII.GetByteCount(result)<=MaxHeader;}
  static bool ValidRequestLine(string line){string[] parts=line.Split(' ');return parts.Length==3&&parts[0].Length>0&&parts[1].StartsWith("/",StringComparison.Ordinal)&&String.Equals(parts[2],"HTTP/1.1",StringComparison.Ordinal);}
  static byte[] ReadHeader(Stream stream){var data=new MemoryStream();for(int i=0;i<MaxHeader;i++){int b=stream.ReadByte();if(b<0||b>127)return null;data.WriteByte((byte)b);if(data.Length>=4){var a=data.GetBuffer();int n=(int)data.Length;if(a[n-4]==13&&a[n-3]==10&&a[n-2]==13&&a[n-1]==10)return data.ToArray();}}return null;}
  // Only phone uploads may carry a large body; it is streamed through instead of buffered.
  static bool UploadLine(string line){string[] parts=line.Split(' ');return parts.Length==3&&parts[0]=="POST"&&parts[1]=="/api/v1/upload";}
  static bool CopyExact(Stream from,Stream to,int count,int timeout){from.ReadTimeout=timeout;byte[] buffer=new byte[81920];while(count>0){int n=from.Read(buffer,0,Math.Min(buffer.Length,count));if(n<=0)return false;to.Write(buffer,0,n);count-=n;}return true;}
  static byte[] ReadExact(Stream stream,int count,int timeout){if(count==0)return new byte[0];stream.ReadTimeout=timeout;byte[] data=new byte[count];int at=0;while(at<count){int n=stream.Read(data,at,count-at);if(n<=0)return null;at+=n;}return data;}
  public void Dispose(){stopped=true;try{listener.Stop();}catch{}foreach(var c in clients.Keys)try{c.Close();}catch{}}
 }
}
