using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Script.Serialization;

namespace Orbit {
 internal sealed class RemoteTailscale:IDisposable {
  readonly object gate=new object(); Process process,startingProcess; LoopbackHostProxy proxy; string url,error,setupUrl; bool starting; int generation;
  public event Action Changed;
  public object Status(){lock(gate)return new {provider="tailscale",starting=starting,url=url,error=error,setupUrl=setupUrl,active=process!=null,proxyPort=proxy==null?0:proxy.Port};}
  public void Start(int port){int attempt;lock(gate){if(process!=null||starting)return;attempt=++generation;starting=true;url=error=setupUrl=null;}string cli=Find();if(cli==null){Fail(attempt,"Tailscale이 설치되어 있지 않습니다.",null);return;}var status=StatusQuery(cli,attempt);if(!Current(attempt))return;var state=Inspect(status.Output);if(!String.IsNullOrEmpty(status.Diagnostic)||!state.Ready){Fail(attempt,StatusFailure(status,state),state.Login);return;}var funnel=Run(cli,"funnel status --json",3000,attempt);if(!String.IsNullOrEmpty(funnel.Diagnostic)){if(Current(attempt))Fail(attempt,"Tailscale Funnel 상태를 확인하지 못했습니다: "+funnel.Diagnostic,null);return;}if(Occupied(funnel.Output)){if(Current(attempt))Fail(attempt,"기존 Tailscale Funnel 설정을 확인할 수 있어 Orbit이 변경하지 않았습니다.",null);return;}if(!Current(attempt))return;LoopbackHostProxy p=null;Process child=null;try{p=new LoopbackHostProxy(port);if(!Current(attempt)){p.Dispose();return;}child=StartProcess(cli,"funnel --https=443 http://127.0.0.1:"+p.Port,attempt);if(child==null){p.Dispose();return;}string expected="https://"+state.Dns.TrimEnd('.');string output=ReadUntil(child,5000,expected);if(!Current(attempt)){Close(child);p.Dispose();return;}if(child.HasExited||!FunnelReady(output,expected)){Close(child);p.Dispose();Fail(attempt,"Tailscale Funnel이 예상한 공개 주소를 알리지 않았습니다.",LoginUrl(output));return;}lock(gate){if(generation!=attempt||!starting){Close(child);p.Dispose();return;}startingProcess=null;process=child;proxy=p;url=expected;starting=false;child.Exited+=(s,e)=>Stopped(child,"Tailscale Funnel이 종료되었습니다.");}if(child.HasExited)Stopped(child,"Tailscale Funnel이 종료되었습니다.");else Raise();}catch(Exception ex){Close(child);if(p!=null)p.Dispose();Fail(attempt,"Tailscale Funnel을 시작하지 못했습니다: "+ex.Message,null);}}
  public object Login(){int attempt;lock(gate){if(process!=null||starting)return Status();attempt=++generation;starting=true;error=setupUrl=null;}string cli=Find();if(cli==null){Fail(attempt,"Tailscale이 설치되어 있지 않습니다.",null);return Status();}var status=StatusQuery(cli,attempt);var state=Inspect(status.Output);if(!Current(attempt))return Status();if(!String.IsNullOrEmpty(status.Diagnostic)){Fail(attempt,StatusFailure(status,state),null);return Status();}string login=state.Login;if(state.NeedsLogin&&String.IsNullOrEmpty(login)){var up=RunCapture(cli,"up --timeout=5s",7000,attempt);login=LoginUrl(up.Output+"\n"+up.Capture);if(String.IsNullOrEmpty(login)&&Current(attempt)){status=StatusQuery(cli,attempt);state=Inspect(status.Output);login=state.Login;}}if(!Current(attempt))return Status();if(!String.IsNullOrEmpty(login)){lock(gate){if(generation!=attempt||!starting)return Status();starting=false;setupUrl=login;error="Tailscale 로그인이 필요합니다.";}Raise();return Status();}if(state.Ready){lock(gate){if(generation==attempt)starting=false;}Raise();return Status();}Fail(attempt,StatusFailure(status,state),null);return Status();}
  public void Stop(){Process p;LoopbackHostProxy x;lock(gate){generation++;p=process??startingProcess;startingProcess=null;process=null;x=proxy;proxy=null;url=error=setupUrl=null;starting=false;}Close(p);if(x!=null)x.Dispose();Raise();}
  bool Current(int attempt){lock(gate)return generation==attempt&&starting;}
  sealed class CommandResult{public string Output="",Diagnostic="",Capture="";}
  CommandResult StatusQuery(string cli,int attempt){var result=Run(cli,"status --json",3000,attempt);if((String.IsNullOrWhiteSpace(result.Output)||Retryable(result.Diagnostic))&&Current(attempt))result=Run(cli,"status --json",3000,attempt);return result;}
  static bool Retryable(string value){return value=="명령 응답 시간이 초과되었습니다."||value=="명령 종료를 기다리는 시간이 초과되었습니다.";}
  static string StatusFailure(CommandResult result,InspectResult state){if(!String.IsNullOrEmpty(state.Login)||state.NeedsLogin)return "Tailscale 로그인이 필요합니다.";if(!String.IsNullOrEmpty(result.Diagnostic))return "Tailscale 상태를 확인하지 못했습니다: "+result.Diagnostic;if(String.IsNullOrWhiteSpace(result.Output))return "Tailscale 상태 응답이 비어 있습니다. 잠시 후 다시 시도해 주세요.";if(!state.HasBackendState)return "Tailscale 상태 응답 형식이 올바르지 않습니다"+(String.IsNullOrEmpty(state.ParseError)?".":" ("+state.ParseError+").");if(String.Equals(state.BackendState,"Stopped",StringComparison.Ordinal))return "Tailscale 연결이 꺼져 있습니다. Tailscale 앱에서 연결해 주세요.";if(state.Running)return "Tailscale의 ts.net DNS 이름을 확인하지 못했습니다.";return "Tailscale 상태가 준비되지 않았습니다: "+state.BackendState;}
  Process StartProcess(string cli,string args,int attempt){var p=new Process{StartInfo=new ProcessStartInfo(cli,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8}};try{lock(gate){if(generation!=attempt||!starting){p.Dispose();return null;}p.EnableRaisingEvents=true;p.Start();startingProcess=p;return p;}}catch{lock(gate){if(generation==attempt)startingProcess=null;}try{p.Dispose();}catch{}throw;}}
  CommandResult Run(string cli,string args,int timeout,int attempt){return Run(cli,args,timeout,attempt,false);}
  CommandResult RunCapture(string cli,string args,int timeout,int attempt){return Run(cli,args,timeout,attempt,true);}
  CommandResult Run(string cli,string args,int timeout,int attempt,bool capture){Process p=null;try{p=StartProcess(cli,args,attempt);if(p==null)return new CommandResult{Diagnostic="요청이 취소되었습니다."};return Read(p,timeout,capture);}catch(Exception ex){return new CommandResult{Diagnostic="명령을 시작하지 못했습니다: "+ex.Message};}finally{if(p!=null){lock(gate){if(startingProcess==p)startingProcess=null;}Close(p);}}}
  static CommandResult Read(Process p,int timeout,bool capture){var output=p.StandardOutput.ReadToEndAsync();var stderr=p.StandardError.ReadToEndAsync();if(!output.Wait(timeout)){Close(p);return new CommandResult{Diagnostic="명령 응답 시간이 초과되었습니다."};}try{p.WaitForExit(1000);if(!p.HasExited)return new CommandResult{Diagnostic="명령 종료를 기다리는 시간이 초과되었습니다."};string stderrText=stderr.Wait(1000)?stderr.Result:"";string captured=capture?Limit(stderrText,2048):"";if(p.ExitCode!=0)return new CommandResult{Output=output.Result,Diagnostic="명령이 종료 코드 "+p.ExitCode+"로 끝났습니다.",Capture=captured};return new CommandResult{Output=output.Result,Capture=captured};}catch(Exception ex){return new CommandResult{Diagnostic="명령 결과를 확인하지 못했습니다: "+ex.Message};}}
  static string Limit(string value,int length){if(String.IsNullOrEmpty(value))return "";return value.Length<=length?value:value.Substring(0,length);}
  static void Close(Process p){try{if(p!=null&&!p.HasExited)p.Kill();}catch{}try{if(p!=null)p.Dispose();}catch{}}
  void Fail(int attempt,string message,string login){lock(gate){if(generation!=attempt||!starting)return;startingProcess=null;starting=false;error=message;setupUrl=login;}Raise();}
  void Stopped(Process expected,string message){LoopbackHostProxy x;lock(gate){if(process!=expected)return;process=null;x=proxy;proxy=null;url=null;starting=false;error=message;}if(x!=null)x.Dispose();Raise();}
  static string Find(){string[] paths={Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),"Tailscale","tailscale.exe"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),"Tailscale","tailscale.exe")};foreach(string p in paths)if(File.Exists(p))return p;return null;}
  static string ReadUntil(Process p,int timeout,string expected){var text=new StringBuilder();var ready=new ManualResetEvent(false);bool captureDone=false;DataReceivedEventHandler add=(s,e)=>{if(e.Data==null)return;lock(text){if(captureDone)return;if(text.Length<8192)text.AppendLine(e.Data);if(FunnelReady(text.ToString(),expected)||LoginUrl(text.ToString())!=null)ready.Set();}};p.OutputDataReceived+=add;p.ErrorDataReceived+=add;try{p.BeginOutputReadLine();p.BeginErrorReadLine();ready.WaitOne(timeout);lock(text)return text.ToString();}finally{p.OutputDataReceived-=add;p.ErrorDataReceived-=add;lock(text)captureDone=true;ready.Dispose();}}
  internal sealed class InspectResult{public bool Running,Ready,NeedsLogin,HasBackendState;public string Dns,Login,BackendState,ParseError;}
  internal static InspectResult Inspect(string text){var r=new InspectResult();r.Login=LoginUrl(text);try{var root=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(text);object auth,backend,selfValue,dnsValue;if(root==null)return r;if(root.TryGetValue("AuthURL",out auth)&&ValidLogin(Convert.ToString(auth)))r.Login=Convert.ToString(auth);if(!root.TryGetValue("BackendState",out backend))return r;r.HasBackendState=true;r.BackendState=Convert.ToString(backend);r.NeedsLogin=String.Equals(r.BackendState,"NeedsLogin",StringComparison.Ordinal);if(!String.Equals(r.BackendState,"Running",StringComparison.Ordinal))return r;r.Running=true;if(!root.TryGetValue("Self",out selfValue))return r;var self=selfValue as Dictionary<string,object>;if(self==null||!self.TryGetValue("DNSName",out dnsValue))return r;r.Dns=Convert.ToString(dnsValue);r.Ready=ValidDns(r.Dns);}catch(Exception ex){r.ParseError=ex.GetType().Name;}return r;}
  static bool ValidDns(string value){return !String.IsNullOrEmpty(value)&&Regex.IsMatch(value,@"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+ts\.net\.?$",RegexOptions.IgnoreCase);}
  internal static bool Occupied(string text){try{var root=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(text);if(root==null)return true;object value;foreach(string key in new[]{"Web","TCP","Foreground"})if(root.TryGetValue(key,out value)&&HasConfig(value))return true;return false;}catch{return true;}}
  static bool HasConfig(object value){if(value==null)return false;var dict=value as Dictionary<string,object>;if(dict!=null)return dict.Count>0;var list=value as System.Collections.IList;if(list!=null)return list.Count>0;if(value is bool)return (bool)value;return !String.IsNullOrWhiteSpace(Convert.ToString(value));}
  internal static bool FunnelReady(string text,string expectedUrl){if(String.IsNullOrEmpty(expectedUrl))return false;string pattern=@"(?:^|\r?\n)Available on the internet:\s*(?:\r?\n)?\s*"+Regex.Escape(expectedUrl.TrimEnd('/'))+@"/?(?=\s|$)";return Regex.IsMatch(text??"",pattern,RegexOptions.IgnoreCase);}
  static bool ValidLogin(string value){Uri u;return Uri.TryCreate(value,UriKind.Absolute,out u)&&u.Scheme=="https"&&String.Equals(u.Host,"login.tailscale.com",StringComparison.OrdinalIgnoreCase);}
  internal static string LoginUrl(string text){var m=Regex.Match(text??"",@"https://login\.tailscale\.com/[A-Za-z0-9_./?=&%-]+",RegexOptions.IgnoreCase);return m.Success&&ValidLogin(m.Value)?m.Value:null;}
  void Raise(){var h=Changed;if(h!=null)h();}public void Dispose(){Stop();}
 }
}
